// SPDX-License-Identifier: GPL-3.0+
package com.armsx2.ui.settingshub

import com.armsx2.navigation.SettingsCategory

/**
 * Settings-search index: the label of every settings-row widget
 * (ToggleRow/SliderRow/SegmentedRow/CollapsibleSection/...) in each settings tab, mapped to
 * its hosting category. Labels that are i18n keys are resolved (and matched against the
 * English source too, so search works in every language); raw-literal labels are matched
 * as-is. Update alongside the settings screens after adding/renaming settings;
 * platforms/android/tools/settings-search-sections.py prints the section chain for each row.
 *
 * [SettingsSearchEntry.sections] lists the CollapsibleSection title keys that wrap the entry
 * (outermost first; empty when the row sits outside every section). A search jump resolves them
 * the same way as labels and opens every one, so the destination is composed and registered
 * before the jump selects it — no section ever composes its rows just to find the target.
 * Section-title entries list themselves, so jumping to a section header opens it too.
 */
internal data class SettingsSearchEntry(
    val text: String,
    val isI18nKey: Boolean,
    val category: SettingsCategory,
    val sections: List<String> = emptyList(),
)

private val BASE_SEARCH_INDEX: List<SettingsSearchEntry> = listOf(
    SettingsSearchEntry("app.bootLogo", true, SettingsCategory.General),
    SettingsSearchEntry("app.library.search", true, SettingsCategory.General),
    SettingsSearchEntry("app.library.recents", true, SettingsCategory.General),
    SettingsSearchEntry("app.library.coverSize", true, SettingsCategory.General),
    SettingsSearchEntry("games.overflow.gridNames", true, SettingsCategory.General),
    SettingsSearchEntry("app.backup.export", true, SettingsCategory.General),
    SettingsSearchEntry("app.backup.import", true, SettingsCategory.General),
    SettingsSearchEntry("app.blockHome", true, SettingsCategory.General),
    SettingsSearchEntry("app.theme", true, SettingsCategory.General),
    SettingsSearchEntry("app.toolbarPosition", true, SettingsCategory.General),
    SettingsSearchEntry("app.launcherRotation", true, SettingsCategory.General),
    SettingsSearchEntry("app.bgColor", true, SettingsCategory.General),
    SettingsSearchEntry("app.menuSfx", true, SettingsCategory.General),
    SettingsSearchEntry("perf.fix.skipBios", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.gamedbFixes", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.skipMpeg", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.fmvSoftware", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.eeTiming", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.instantDma", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.blitFps", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.ophFlag", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.gifFifo", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.dmaBusy", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.vif1Stall", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.iBit", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.fullVu0Sync", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.vuAddSub", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.vuOverflow", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.extraXgkick", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.goemonTlb", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.fix.vuSync", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.hack.mtvu", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.instantVu1", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.vuFlagHack", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.fastCdvd", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.intcStat", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.waitLoop", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.vuNeonFusions", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.skipVuStallSim", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.deferVuWrites", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.hack.skipDupeFrames", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("perf.eeCycleRate.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.eeCycleSkip.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.speedLimit.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.displayFpsCap.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.ntscFramerate.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.palFramerate.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.frameSkip.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.lowLatencyMode.label", true, SettingsCategory.Performance),
    SettingsSearchEntry("perf.speedhackProfile.label", true, SettingsCategory.Performance),
    SettingsSearchEntry("perf.displayResolution.label", true, SettingsCategory.Performance),
    SettingsSearchEntry("perf.screenRes.label", true, SettingsCategory.Performance),
    SettingsSearchEntry("perf.sustainedPerformance.label", true, SettingsCategory.Performance),
    SettingsSearchEntry("perf.adpf.label", true, SettingsCategory.Performance),
    SettingsSearchEntry("perf.eeFpuClamping.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.vuClamping.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.vu1Clamping.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.eeFpuRoundMode.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.vu0RoundMode.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.vu1RoundMode.label", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.speedhacks.title", true, SettingsCategory.Performance, listOf("perf.speedhacks.title")),
    SettingsSearchEntry("perf.gamedbFixes.title", true, SettingsCategory.Advanced, listOf("perf.gamedbFixes.title")),
    SettingsSearchEntry("perf.advancedSpeedhacks.title", true, SettingsCategory.Performance, listOf("perf.advancedSpeedhacks.title")),
    SettingsSearchEntry("VSync", false, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.shadeboost.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.gsBackThread.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.fxaa.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.shaderChain.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.shaderChain.preset.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.loadTexturePacks.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.asyncTextureLoading.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.precacheTexturePacks.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.textureUpscale.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.dumpReplaceableTextures.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.texturePackOsd.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.rov.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.coalesceRenderPasses.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("pad.pressureAmount.label", true, SettingsCategory.Controls, listOf("pad.section.onScreenControls")),
    SettingsSearchEntry("renderer.forceMaliFbFetch.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.angleOpenGL.label", true, SettingsCategory.Graphics),
    SettingsSearchEntry("renderer.accurateAlphaTest.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.hwAa1.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.hwMipmapping.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.brightness.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.contrast.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.saturation.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.gamma.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.fsr1.sharpness.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.cas.sharpness.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.displayMode.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.fmvAspect.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.orientation.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.portraitPosition.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.autoProgressive.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("perf.affinity.label", true, SettingsCategory.Performance),
    SettingsSearchEntry("renderer.textureFiltering.label", true, SettingsCategory.Graphics, listOf("renderer.section.texturesFiltering")),
    SettingsSearchEntry("renderer.texturePreloading.label", true, SettingsCategory.Graphics, listOf("renderer.section.texturesFiltering")),
    SettingsSearchEntry("renderer.displayFilter.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    // The FSR1 switch became the Display-upscaler picker when SGSR joined it; searching for the
    // old key would land on a row that no longer exists.
    // Missing from the index entirely, so nobody could search their way to it -- which is
    // exactly what #629 reported ("If one exists, I can't seem to find it").
    SettingsSearchEntry("overlay.toggle.fastForwardPopups", true, SettingsCategory.Graphics),
    SettingsSearchEntry("overlay.toggle.freeSoftwareNotice", true, SettingsCategory.Graphics),
    SettingsSearchEntry("renderer.upscaler.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.cas.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.blendingAccuracy.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.trilinear.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.anisotropic.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.gpuProfile.label", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("renderer.upscale.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.deinterlacing.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.hardwareDownloadMode.label", true, SettingsCategory.Graphics, listOf("renderer.section.texturesFiltering")),
    SettingsSearchEntry("renderer.tvShader.label", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.section.displayResolution", true, SettingsCategory.Graphics, listOf("renderer.section.displayResolution")),
    SettingsSearchEntry("renderer.section.texturesFiltering", true, SettingsCategory.Graphics, listOf("renderer.section.texturesFiltering")),
    SettingsSearchEntry("renderer.section.displayEffects", true, SettingsCategory.Graphics, listOf("renderer.section.displayEffects")),
    SettingsSearchEntry("renderer.section.texturePacks", true, SettingsCategory.Graphics),
    SettingsSearchEntry("renderer.section.blendingAdvanced", true, SettingsCategory.Graphics, listOf("renderer.section.blendingAdvanced")),
    SettingsSearchEntry("audio.mute.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.synchronization.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.swapChannels.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.spu2Simd.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.openSles.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.lightweight.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.volume.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.buffer.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.outputLatency.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("audio.fastForwardVolume.label", true, SettingsCategory.Audio),
    SettingsSearchEntry("pad.rumble.label", true, SettingsCategory.Controls, listOf("pad.section.playerRumble")),
    SettingsSearchEntry("pad.gyro.mode.label", true, SettingsCategory.Controls, listOf("pad.gyro.section")),
    SettingsSearchEntry("pad.gyro.sensitivity.label", true, SettingsCategory.Controls, listOf("pad.gyro.section")),
    SettingsSearchEntry("pad.gyro.splitAxes.label", true, SettingsCategory.Controls, listOf("pad.gyro.section")),
    SettingsSearchEntry("pad.gyro.steerStick.label", true, SettingsCategory.Controls, listOf("pad.gyro.section")),
    SettingsSearchEntry("pad.gyro.smoothing.label", true, SettingsCategory.Controls, listOf("pad.gyro.section")),
    SettingsSearchEntry("pad.gyro.invertX.label", true, SettingsCategory.Controls, listOf("pad.gyro.section")),
    SettingsSearchEntry("pad.gyro.invertY.label", true, SettingsCategory.Controls, listOf("pad.gyro.section")),
    SettingsSearchEntry("pad.multitap.label", true, SettingsCategory.Controls, listOf("pad.section.playerRumble")),
    SettingsSearchEntry("pad.leftStick.swapXY.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.leftStick.invertX.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.leftStick.invertY.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.rightStick.swapXY.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.rightStick.invertX.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.rightStick.invertY.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.dpadAsLeftStick.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.touchHaptics.label", true, SettingsCategory.Controls, listOf("pad.section.onScreenControls")),
    SettingsSearchEntry("pad.onScreenControls.label", true, SettingsCategory.Controls, listOf("pad.section.onScreenControls")),
    SettingsSearchEntry("touch.editor.multiTouchOn", true, SettingsCategory.Controls, listOf("pad.section.onScreenControls")),
    SettingsSearchEntry("pad.stickFeel.deadzone.label", true, SettingsCategory.Controls, listOf("pad.leftStickFeel.title", "pad.rightStickFeel.title")),
    SettingsSearchEntry("pad.stickFeel.outerDeadzone.label", true, SettingsCategory.Controls, listOf("pad.leftStickFeel.title", "pad.rightStickFeel.title")),
    SettingsSearchEntry("pad.stickFeel.antiDeadzone.label", true, SettingsCategory.Controls, listOf("pad.leftStickFeel.title", "pad.rightStickFeel.title")),
    SettingsSearchEntry("pad.stickFeel.sensitivity.label", true, SettingsCategory.Controls, listOf("pad.leftStickFeel.title", "pad.rightStickFeel.title")),
    SettingsSearchEntry("pad.stickFeel.acceleration.label", true, SettingsCategory.Controls, listOf("pad.leftStickFeel.title", "pad.rightStickFeel.title")),
    SettingsSearchEntry("pad.editing.label", true, SettingsCategory.Controls, listOf("pad.section.playerRumble")),
    SettingsSearchEntry("pad.leftStick.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.rightStick.label", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.section.playerRumble", true, SettingsCategory.Controls, listOf("pad.section.playerRumble")),
    SettingsSearchEntry("pad.section.analogSticks", true, SettingsCategory.Controls, listOf("pad.section.analogSticks")),
    SettingsSearchEntry("pad.section.buttonMapping", true, SettingsCategory.Controls, listOf("pad.section.buttonMapping")),
    SettingsSearchEntry("pad.section.onScreenControls", true, SettingsCategory.Controls, listOf("pad.section.onScreenControls")),
    SettingsSearchEntry("pad.section.macros", true, SettingsCategory.Controls, listOf("pad.section.macros")),
    SettingsSearchEntry("hotkeys.exitToLauncher.label", true, SettingsCategory.Hotkeys),
    SettingsSearchEntry("network.enableDev9Ethernet", true, SettingsCategory.Network),
    SettingsSearchEntry("network.interceptDhcp", true, SettingsCategory.Network),
    SettingsSearchEntry("network.autoSubnetMask", true, SettingsCategory.Network),
    SettingsSearchEntry("network.autoGateway", true, SettingsCategory.Network),
    SettingsSearchEntry("network.logDhcp", true, SettingsCategory.Network),
    SettingsSearchEntry("network.logDns", true, SettingsCategory.Network),
    SettingsSearchEntry("network.enableDev9VirtualHdd", true, SettingsCategory.Network),
    SettingsSearchEntry("network.emulateUsbKeyboard", true, SettingsCategory.Network),
    SettingsSearchEntry("network.ethernetApi", true, SettingsCategory.Network),
    SettingsSearchEntry("network.primaryDns", true, SettingsCategory.Network),
    SettingsSearchEntry("network.secondaryDns", true, SettingsCategory.Network),
    SettingsSearchEntry("overlay.toggle.gpuUsage", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.cpuUsage", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.fps", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.vps", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.emulationSpeed", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.internalResolution", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.gsStatistics", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.frameTimesGraph", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.hardwareInfo", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.gpuPipelineStats", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.emulatorVersion", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.settingsSummary", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.controlInputs", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.onScreenNotifications", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.fastForwardPopups", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.toggle.freeSoftwareNotice", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.osdSize.label", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.osdColor.label", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.osdPosition.label", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.quickMenuSide.label", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.uiSize.label", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("overlay.uiFontSize.label", true, SettingsCategory.OnScreen),
    SettingsSearchEntry("fixes.antiBlur.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.screenOffsets.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.showOverscan.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.disableInterlaceOffset.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.syncToHostRefresh.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.disableFramebufferFetch.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.hwAccurateAlphaTest.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.disableVertexShaderExpand.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.useBlitSwapChain.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.disableShaderCache.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.integerScaling.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.alignSprite.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.mergeSprite.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.wildArmsOffset.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.unscaledPaletteDraw.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.manualHardwareFixes.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.gpuPaletteConversion.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.cpuFramebufferConversion.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.readTargetsWhenClosing.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.preloadFrameData.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.estimateTextureRegion.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.drawBuffering.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.disableDepthEmulation.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.disablePartialInvalidation.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.disableSafeFeatures.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.disableRenderFixes.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.spinGpuReadbacks.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.spinCpuReadbacks.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.autoFlushSw.label", true, SettingsCategory.Advanced, listOf("fixes.section.software")),
    SettingsSearchEntry("fixes.mipmapSw.label", true, SettingsCategory.Advanced, listOf("fixes.section.software")),
    SettingsSearchEntry("fixes.textureOffsetX.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.textureOffsetY.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.skipDrawStart.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.skipDrawEnd.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.swThreads.label", true, SettingsCategory.Advanced, listOf("fixes.section.software")),
    SettingsSearchEntry("fixes.swThreadTileHeight.label", true, SettingsCategory.Advanced, listOf("fixes.section.software")),
    SettingsSearchEntry("fixes.overrideTextureBarriers.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.dithering.label", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.upscalingFixes.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.halfPixelOffset.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.roundSprite.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.bilinearDirty.label", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.autoFlush.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.textureInsideRt.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.gpuTargetClut.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.cpuSpriteBw.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.cpuClutRender.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.limit24BitDepth.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.cpuSpriteRender.label", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.section.display", true, SettingsCategory.Advanced, listOf("fixes.section.display")),
    SettingsSearchEntry("fixes.section.upscaling", true, SettingsCategory.Advanced, listOf("fixes.section.upscaling")),
    SettingsSearchEntry("fixes.section.hardware", true, SettingsCategory.Advanced, listOf("fixes.section.hardware")),
    SettingsSearchEntry("fixes.section.software", true, SettingsCategory.Advanced, listOf("fixes.section.software")),
    SettingsSearchEntry("EE (R5900)", false, SettingsCategory.Advanced, listOf("tab.recompiler")),
    SettingsSearchEntry("IOP (R3000)", false, SettingsCategory.Advanced, listOf("tab.recompiler")),
    SettingsSearchEntry("VU0", false, SettingsCategory.Advanced, listOf("tab.recompiler")),
    SettingsSearchEntry("VU1", false, SettingsCategory.Advanced, listOf("tab.recompiler")),
    SettingsSearchEntry("Fastmem", false, SettingsCategory.Advanced, listOf("tab.recompiler")),
    SettingsSearchEntry("fixes.section.pine", true, SettingsCategory.Advanced, listOf("fixes.section.pine")),
    SettingsSearchEntry("fixes.pine.enable", true, SettingsCategory.Advanced, listOf("fixes.section.pine")),
    SettingsSearchEntry("patches.enablePatches.label", true, SettingsCategory.Patches),
    SettingsSearchEntry("patches.cheats.label", true, SettingsCategory.Patches),
    SettingsSearchEntry("patches.widescreen.label", true, SettingsCategory.Patches),
    SettingsSearchEntry("patches.noInterlacing.label", true, SettingsCategory.Patches),
    SettingsSearchEntry("patches.hostFs.label", true, SettingsCategory.Patches),
)

/**
 * Everything searchable, plus whatever the flavour adds.
 *
 * The frame-generation rows come from a flavoured list rather than sitting in the one above. In
 * the play build they would otherwise still be indexed while the section they point at was
 * compiled out — searching would offer a result that renders its own key as its title and leads
 * nowhere.
 */
internal val SETTINGS_SEARCH_INDEX: List<SettingsSearchEntry> = BASE_SEARCH_INDEX + LSFG_SEARCH_INDEX
