// SPDX-FileCopyrightText: 2002-2026 PCSX2 Dev Team
// SPDX-License-Identifier: GPL-3.0+

// Namco System 246/256 arcade hardware, ported from PCSX2x6
// (https://github.com/PS2Homebrew-arcade/pcsx2x6) by Matías Israelson (El_isra), Tovarichtch and
// DiscoStarslayer. Only reached while an arcade game runs (Arcade::IsActive(), common/ARCADE.h).

#pragma once

/**
 * @file ACATA.h
 * ATA interface through the NAMCO board of the SYSTEM246/256
 * used by ACATA.IRX, which is used by ACDVDV and ACATAD for using disc readers or hard drives on system2x6 units
 */

#include "Config.h"
#include "MemoryTypes.h"
#include "common/Pcsx2Types.h"
#include "common/Pcsx2Defs.h"
#include "common/ARCADE.h"
#include <map>

#include <string>
#include <thread>
#include <atomic>
#include <mutex>
#include <condition_variable>

#include "common/RedtapeWindows.h"
#include "common/Path.h"

#include "ACATA_internal.h"
#include "ACATAPI.h"

#define ACATA_LOG(fmt, ...) if (EmuConfig.Arcade.ATAVerboseReads) Console.WriteLn(Color_Gray, "ACATA:" fmt __VA_OPT__(,) __VA_ARGS__)

#define ACATA_R_DATA                0x16000000  // Read/Write PIO data bytes
#define ACATA_R_FEATURE             0x16010000  // [W] Used to control command specific interface features.
#define ACATA_R_ERROR          ACATA_R_FEATURE  // [R] Used to retrieve any error generated by the last ATA command executed.	
#define ACATA_R_NSECTOR             0x16020000  // Number of sectors to read/write (0 is a special value).
#define ACATA_R_SECTOR              0x16030000  // This is CHS / LBA28 / LBA48 specific.
#define ACATA_R_LCYL                0x16040000  // Partial Disk Sector address.
#define ACATA_R_HCYL                0x16050000  // Partial Disk Sector address.
#define ACATA_R_SELECT              0x16060000  // Used to select a drive and/or head. Supports extra address/flag bits. 0x10 bit determines drive
#define ACATA_R_STATUS              0x16070000  // [R] Used to read the current status.
#define ACATA_R_COMMAND         ACATA_R_STATUS  // [W] Used to send ATA commands to the device.
#define ACATA_R_STATUS_ALT          0x16160000  // [R] A duplicate of the Status Register which does not affect interrupts.
#define ACATA_R_CONTROL     ACATA_R_STATUS_ALT  // [W] Used to reset the bus or enable/disable interrupts.


#define ACATA_RANGE              0x1600
#define ACATA_UNIT0              0x0  // 16 * (unitIndex != 0)
#define ACATA_UNIT1              0x10 // 16 * (unitIndex != 0)

#define FEAT_DMA 0x1 // the requested transfer will be done over DMA, not PIO
#define ACATA_ISDMA (ACATA::R_FEATURE & FEAT_DMA) // `*0x16010000 & 1` indicates DMA will be used


namespace ACATA 
{
    extern u32 last_read;
    extern u32 last_write;
    extern u32 cmd_handled;
    extern u32 cmd_handledc;
    extern atapi_packet_t ata_c_packet;
    extern std::string imgpath;
    extern u16 R_DATA; // Read/Write PIO data bytes
    extern u16 R_FEATURE; // [W] Used to control command specific interface features.
    extern u16 R_ERROR; // [R] Used to retrieve any error generated by the last ATA command executed.	
    extern u16 R_NSECTOR; // Number of sectors to read/write (0 is a special value).
    extern u16 R_SECTOR; // This is CHS / LBA28 / LBA48 specific.
    extern u16 R_LCYL; // Partial Disk Sector address.
    extern u16 R_HCYL; // Partial Disk Sector address.
    extern u16 R_SELECT; // Used to select a drive and/or head. Supports extra address/flag bits. 0x10 bit determines drive
    extern u16 R_STATUS; // [R] Used to read the current status.
    extern u16 R_COMMAND; // [W] Used to send ATA commands to the device.
    extern u16 R_STATUS_ALT; // [R] A duplicate of the Status Register which does not affect interrupts.
    extern u16 R_CONTROL; // [W] Used to reset the bus or enable/disable interrupts.
    u16 read16(u32 addr);               // handle writes to ACATA MMIO
    void write16(u32 addr, u16 val);    // handle reads  to ACATA MMIO
	u16 handle_dataR(u32 addr);          // handle reads  to 0x16000000 while ATA command
    void handle_dataW(u32 addr, u16 val); // handle writes to 0x16000000 while ATA command
    void handle_cmd(u16 val);   // handle writes to 0x16070000, usually: ATA command requests
    extern ACMEDIATYPE MediaType;
    namespace TH { //dedicated namespace for thread related code
        
	    extern std::mutex ioMutex;
        extern bool b_isIdle,
            ioWrite,
            ioRead,
            isCHD;
	    extern std::condition_variable Idle_cv, ioReady;
        extern FILE* IMAGE;
        extern s64 IMAGESIZE;
        extern u32 sectorsize; //512 for hdd and 2048 for Disc (?) check it
        extern u32 unitbytes;   //bytes per sector unit in a raw disc image file (0 = plain 2048-byte units)
        extern u32 unitdataoff; //offset of the 2048-byte payload inside a unit
        extern std::string open_error; //user-facing reason when IO_OpenImage rejects the image
        extern u32 nsector;
        extern s64 LBA;

        // Reads the sectors the last READ DMA asked for straight into addr, never more than size bytes,
        // the DMA's own transfer. False when the image cannot supply them: the caller reports a drive
        // error, and what was not read is zeroed.
        bool IO_Read(u32* addr, u32 size);
        void IO_Write(u32* addr, u32 size);
        int IO_OpenImage();
        int IO_CloseImage();
    }
    void SetImage(std::string path, ACMEDIATYPE media); // the media image to serve (path or content:// URI)
    // ARMSX2: where a CHD hard drive's writes are kept, beside the game's SRAM (ChdImage::OpenWrites).
    extern std::string writespath;
    void SetWritesFile(std::string path);
    // The drive as a freshly started emulator has it: every register and transfer zero, as at a game's
    // start and every reset of it (ARMSX2: the board outlives a game here; PCSX2x6 started a new process).
    void Reset();
}
